"""slug

Revision ID: cab628a16fdb
Revises: c0ecdb396fe1
Create Date: 2022-04-11 14:07:30.066360

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cab628a16fdb'
down_revision = 'c0ecdb396fe1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('article', 'slug',
               existing_type=sa.VARCHAR(length=140),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('article', 'slug',
               existing_type=sa.VARCHAR(length=140),
               nullable=False)
    # ### end Alembic commands ###
